---
- name: Create Vector user and group
  ansible.builtin.group:
    name: "{{ vector_group }}"
    state: present

- name: Create Vector user and home directory
  ansible.builtin.user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    home: "/home/{{ vector_user }}"
    shell: "/bin/bash"
    createhome: true

- name: Download Vector distribution
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_os_arh }}-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-{{ vector_os_arh }}-unknown-linux-gnu.tar.gz"
    mode: "0644"

- name: Extract Vector distribution
  ansible.builtin.unarchive:
    src: "/tmp/vector-{{ vector_os_arh }}-unknown-linux-gnu.tar.gz"
    dest: "/opt/vector"
    remote_src: true

- name: Vector. Install vector binary file
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ vector_bin_path }}"
    dest: "/usr/bin/"
    mode: "0755"
    owner: root
    group: root

- name: Vector. Create etc directory
  become: true
  ansible.builtin.file:
    path: "/etc/vector"
    state: directory
    mode: "0755"

- name: Vector. Create Vector config vector.yaml
  become: true
  ansible.builtin.template:
    src: "templates/vector/vector.j2"
    dest: "/etc/vector/vector.yaml"

- name: Vector. Create vector.service daemon
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/opt/vector/vector-{{ vector_os_arh }}-unknown-linux-gnu/etc/systemd/vector.service"
    dest: "/lib/systemd/system/"
    mode: "0644"
    owner: root
    group: root

- name: Vector. Modify vector.service file ExecStart
  become: true
  ansible.builtin.replace:
    backup: true
    path: "/lib/systemd/system/vector.service"
    regexp: "^ExecStartPre=/usr/bin/vector validate$"
    replace: "ExecStartPre=/usr/bin/vector validate --config-yaml /etc/vector/vector.yaml"
  notify: Restart Vector service

- name: Vector. Modify vector.service file ExecStartPre
  become: true
  ansible.builtin.replace:
    backup: true
    path: "/lib/systemd/system/vector.service"
    regexp: "^ExecStart=/usr/bin/vector$"
    replace: "ExecStart=/usr/bin/vector --config-yaml /etc/vector/vector.yaml"
  notify: Restart Vector service

- name: Vector. Create user vector
  become: true
  ansible.builtin.user:
    create_home: false
    name: "{{ vector_user }}"
           
- name: Vector. Create data_dir
  become: true
  ansible.builtin.file:
    path: "{{ vector_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"